- src/app/page.tsx
- src/config/index.ts
- Removed unwanted console.logs
> removed logs

- package.json
- yarn.lock
- Updates copilot-node-sdk version
> updated copilot-node-sdk to 1.1.3

- next.config.js
- src/app/components/EditorInterface.tsx
[Banner Image Optimizations](https://linear.app/copilotplatforms/issue/OUT-60/banner-image-optimizations)
> Out 60 Banner Image Optimizations

- src/components/tiptap/floatingMenu/floatingMenuSuggestion.tsx
[Remove Embed from Slash Command List](https://linear.app/copilotplatforms/issue/OUT-50/remove-embed-from-slash-command-list)
> OUT-50 Remove Embed from Slash Command List

- src/app/components/SideBarInterface.tsx
- src/app/page.tsx
- src/types/common.ts
- src/types/interfaces.ts
- src/utils/generateRandomHexColor.ts
adds profile picture in the dropdown
[Client Preview Dropdown Improvements](https://linear.app/copilotplatforms/issue/OUT-54/client-preview-dropdown-improvements)
> OUT-54 Client Preview Dropdown Improvements

- src/app/client-preview/page.tsx
- src/app/components/EditorInterface.tsx
- src/app/components/Footer.tsx
[Enter key should insert client variable value in Client Home](https://linear.app/copilotplatforms/issue/OUT-59/enter-key-should-insert-client-variable-value-in-client-home)
> OUT-59 Enter key should insert client variable value in Client Home

- src/app/client-preview/page.tsx
- src/app/components/EditorInterface.tsx
- src/app/components/Footer.tsx
- src/components/autofillFields/AutofillFields.tsx
[Fix display of multiSelect autofill fields](https://linear.app/copilotplatforms/issue/OUT-52/fix-display-of-multiselect-autofill-fields)
> OUT-52 Fix display of multiSelect autofill fields

- defaultState.ts
Some minor updates to update the default state
> update default state

- defaultState.ts
Default state is a bit cramped right now.
> Add extra line

- src/app/api/settings/route.ts
> fix: settings data structure

- src/app/client-preview/page.tsx
[Custom field autofill fields are not populating on client-side](https://linear.app/copilotplatforms/issue/OUT-110/custom-field-autofill-fields-are-not-populating-on-client-side)
> OUT-110 Fix autofield populating issue on client-preview

- src/app/client-preview/page.tsx
- src/app/components/EditorInterface.tsx
[More fixes on Display of multiSelect autofill field](https://linear.app/copilotplatforms/issue/OUT-111/more-fixes-on-display-of-multiselect-autofill-field)
> OUT-111 More fixes on display of multiSelect autofill field

- src/app/client-preview/page.tsx
- src/app/page.tsx
Ref: 
- [OUT-113](https://linear.app/copilotplatforms/issue/OUT-113/error-unable-to-authorize-copilot-sdk)
- [OUT-139](https://linear.app/copilotplatforms/issue/OUT-139/referenceerror-token-is-not-defined)
- [OUT-136](https://linear.app/copilotplatforms/issue/OUT-136/error-unable-to-authorize-copilot-sdk)
Changes:
- Add zod validation to make sure we receive token in URL params
> OUT-113 | OUT-136 | OUT-139 | Error: Unable to authorize Copilot SDK

- src/app/components/EditorInterface.tsx
- src/app/globals.css
- src/components/autofillFields/AutofillFields.tsx
- src/components/tiptap/autofieldSelector/AutofillComponent.tsx
- src/components/tiptap/autofieldSelector/ext_autofill.ts
- src/utils/tiptapEditorUtils.ts
[Improved experience for selecting autofill fields](https://linear.app/copilotplatforms/issue/OUT-55/clicking-on-autofill-field-removes-styling)
> OUT-55 | OUT-42 Improved experience for selecting autofill fields

- src/app/components/EditorInterface.tsx
- src/types/interfaces.ts
[More fixes on display of multiSelect autofill field](https://linear.app/copilotplatforms/issue/OUT-111/more-fixes-on-display-of-multiselect-autofill-field)
> More fixes on display of multiSelect autofill field

- src/app/client-preview/page.tsx
- Fixes autofield populating issue in client-preview
> custom field populating fix in client-preview

- src/components/tiptap/autofieldSelector/ext_autofill.ts
> adds fixes to autofill fields

- src/components/colorPicker/ColorPicker.tsx
Ref: [OUT-89](https://linear.app/copilotplatforms/issue/OUT-89/changed-background-color-to-background)
Changes:
- Change sidebar label text
> OUT-89 | Changed “Background color” to “Background”

- .prettierignore
- src/app/api/settings/route.ts
- src/app/client-preview/page.tsx
- src/app/components/ClientPreview.tsx
- src/app/components/EditorInterface.tsx
- src/app/components/Footer.tsx
- src/components/NotificationsModal/index.tsx
- src/components/display/DisplayTasksToggle.tsx
- src/components/tiptap/notificationWidget/NotificationWidget.tsx
- src/types/notifications.ts
- src/types/setting.ts
- src/utils/handleBannerImageUpload.ts
- src/utils/notifications.ts
Ref: https://linear.app/copilotplatforms/issue/OUT-179/show-default-template-in-client-portal-if-setting-is-not-saved
- Show default template in client portal if setting is not saved
> OUT-179 handle default state in client preview

- .prettierignore
- src/app/api/settings/route.ts
- src/app/client-preview/page.tsx
- src/app/components/ClientPreview.tsx
- src/app/components/EditorInterface.tsx
- src/app/components/Footer.tsx
- src/components/NotificationsModal/index.tsx
- src/components/display/DisplayTasksToggle.tsx
- src/components/tiptap/notificationWidget/NotificationWidget.tsx
- src/types/notifications.ts
- src/types/setting.ts
- src/utils/handleBannerImageUpload.ts
- src/utils/notifications.ts
Ref: https://linear.app/copilotplatforms/issue/OUT-178/handle-displaying-notifications-based-on-the-count
- Handle displaying notifications based on the count
> Out 178 Handle displaying notifications based on the count

- .prettierignore
- src/app/api/settings/route.ts
- src/app/client-preview/page.tsx
- src/app/components/ClientPreview.tsx
- src/app/components/EditorInterface.tsx
- src/app/components/Footer.tsx
- src/components/NotificationsModal/index.tsx
- src/components/atoms/RedirectButton.tsx
- src/components/display/DisplayTasksToggle.tsx
- src/components/tiptap/notificationWidget/NotificationWidget.tsx
- src/types/notifications.ts
- src/types/setting.ts
- src/utils/handleBannerImageUpload.ts
- src/utils/notifications.ts
Ref: https://linear.app/copilotplatforms/issue/OUT-173/disconnect-app-bridge-on-preview-mode
- Doesn't navigate IU to the widget links if clicked in preview mode
> Out 173 Disconnect App Bridge on preview mode

- src/app/components/EditorInterface.tsx
- src/components/NotificationsModal/ModalCheckbox.tsx
- src/components/NotificationsModal/index.tsx
- src/components/tiptap/notificationWidget/NotificationWidget.tsx
- Adds miscellaneous improvements
> Out 197 Miscellaneous

- src/app/components/ClientPreview.tsx
- src/app/components/EditorInterface.tsx
- src/app/components/SideBarInterface.tsx
- src/components/NotificationsModal/ModalCheckbox.tsx
- src/components/NotificationsModal/index.tsx
- src/components/tiptap/notificationWidget/NotificationWidget.tsx
Ref: https://linear.app/copilotplatforms/issue/OUT-189/when-i-toggle-display-tasks-on-for-the-first-time-the-widget-has-no
- show widget tasks on initial load
> Out 189 When I toggle Display Tasks on for the first time, the widget has no rows inside it

- src/app/api/notifications/route.ts
- src/app/components/ClientPreview.tsx
- src/app/components/EditorInterface.tsx
- src/app/components/SideBarInterface.tsx
- src/components/NotificationsModal/ModalCheckbox.tsx
- src/components/NotificationsModal/index.tsx
- src/components/tiptap/notificationWidget/NotificationWidget.tsx
- src/hooks/useAppData.tsx
- src/types/interfaces.ts
Ref: https://linear.app/copilotplatforms/issue/OUT-193/total-tasks-should-only-count-apps-that-are-visible
- Refactors notification tasks showing logic
> Out 193 Total tasks should only count apps that are visible

- src/app/globals.css
Ref: https://linear.app/copilotplatforms/issue/OUT-232/issue-with-text-overflow-in-callouts-on-mobile
- fixes overflow of text in the callout component
> OUT 232 Issue with text overflow in callouts on mobile

- src/app/components/ClientPreview.tsx
- Fixes auto scroll issue for client-preview
> fix: auto scroll

- src/components/display/DisplayTasksToggle.tsx
- src/components/tiptap/notificationWidget/NotificationWidget.tsx
- src/hooks/useAppData.tsx
> OUT-838 Change the word "Tasks" in Client Home to "Actions"

- src/components/tiptap/image/image.ts
- src/components/tiptap/notificationWidget/NotificationWidget.tsx
- src/components/tiptap/notificationWidget/ext_notification_widget.tsx
[RangeError: Position 1503 outside of fragment ](https://linear.app/copilotplatforms/issue/OUT-1567/rangeerror-position-1503-outside-of-fragment-headingwelcome-mention)
> OUT-1567 | RangeError: Position 1503 outside of fragment 

- src/components/tiptap/autofieldSelector/autofillMenuSuggestion.ts
- src/utils/token.ts
This is intended to fix race condition where token is not parseable at first try
> OUT-1683: Fix Zod error - attempt to read token multiple times

- src/app/client-preview/page.tsx
- src/app/components/EditorInterface.tsx
- src/components/autofillFields/AutofillFields.tsx
- src/components/tiptap/autofieldSelector/AutofillMenu.tsx
- src/components/tiptap/autofieldSelector/autofillMenuSuggestion.ts
- src/components/tiptap/floatingMenu/FloatingMenu.tsx
- src/utils/customLabels.ts
> OUT-2310, OUT-2287, OUT-2246 | client home crashed with undefined on replaceAll
