- src/components/colorPicker/ColorPicker.tsx
[Support text-based input of hex code for background color](https://linear.app/copilotplatforms/issue/OUT-58/support-text-based-input-of-hex-code-for-background-color)
> OUT-58 Support text-based input of hex code for background color

- src/app/client-preview/page.tsx
- src/app/components/EditorInterface.tsx
- src/app/components/Footer.tsx
[Fallback image is not shown in client portal](https://linear.app/copilotplatforms/issue/OUT-74/fallback-image-is-not-shown-in-client-portal)
> OUT-74 Fallback image logic

- src/types/common.ts
This PR removes portalName from the MeResponseSchema object. That property was removed from the response. It also seems like it's never used in client home, so we can safely delete this line.
> fix: portalName is no longer part of this payload

- src/app/client-preview/page.tsx
- src/app/components/EditorInterface.tsx
- src/app/components/Footer.tsx
- src/utils/constants.ts
[Banner image gets reset on first save](https://linear.app/copilotplatforms/issue/OUT-109/banner-image-gets-reset-on-first-save)
> OUT-109 Banner image gets reset on first save

- src/app/components/EditorInterface.tsx
[Client Home crashing when client.company turns into a link](https://linear.app/copilotplatforms/issue/OUT-135/client-home-crashing-when-clientcompany-turns-into-a-link)
> OUT-135 Client Home crashing when client.company turns into a link

- src/components/autofillFields/AutofillFields.tsx
[Include all autofill fields of the client in sidebar, even if empty](https://linear.app/copilotplatforms/issue/OUT-128/include-all-autofill-fields-of-the-client-in-sidebar-even-if-empty)
> OUT-128 Include all autofill fields of the client in sidebar, even if empty

- src/app/components/ClientPreview.tsx
- src/app/components/EditorInterface.tsx
- src/app/components/SideBarInterface.tsx
- src/components/NotificationsModal/ModalCheckbox.tsx
- src/components/NotificationsModal/index.tsx
- src/components/tiptap/notificationWidget/NotificationWidget.tsx
Ref: https://linear.app/copilotplatforms/issue/OUT-192/singularplural-issues
Ref: https://linear.app/copilotplatforms/issue/OUT-191/weird-vertical-alignment-in-the-widget
- Fixes vertical alignment issue
- Fixes singular plural issue
> Out 192 Singular Plural Issue | Alignment Issue

- src/components/tiptap/notificationWidget/NotificationWidget.tsx
The `/s` copy didn't look so good after all.
> update plural logic for cleaner copy

- src/app/client-preview/page.tsx
- src/app/components/ClientPreview.tsx
- src/app/components/EditorInterface.tsx
Ref: https://linear.app/copilotplatforms/issue/OUT-202/default-banner-image-shows-up-to-clients-when-banner-image-is-empty
Ref: https://linear.app/copilotplatforms/issue/OUT-207/switching-in-and-out-of-preview-causes-issues-with-autofill-fields
- Fixes issue for default banner image showing in client preview even though image is not set by IU
- Fixes autofill field issue
> Out 202 207 Banner image issue and autofill issue

- src/app/client-preview/page.tsx
- src/app/components/ClientPreview.tsx
- src/app/components/EditorInterface.tsx
- src/app/globals.css
- src/components/tiptap/floatingMenu/FloatingMenu.tsx
- src/components/tiptap/floatingMenu/floatingMenuSuggestion.tsx
- src/components/tiptap/iframe/IFrameInput.tsx
- src/components/tiptap/iframe/ext_iframe.ts
- src/components/tiptap/notificationWidget/NotificationWidget.tsx
- src/context/index.tsx
- src/utils/tiptapEditorUtils.ts
Ref: https://linear.app/copilotplatforms/issue/OUT-106/add-embed-type-to-client-home
- Adds embed type to the editor
> OUT-106 Add Embed Type

- src/components/NotificationsModal/index.tsx
Ref: https://linear.app/copilotplatforms/issue/OUT-220/a-few-lines-in-the-right-sidebar-are-white-instead-of-black-when-the
- Fixes appearing of unwanted lines when the notification widget modal is open
> OUT 220 A few lines in the right sidebar are white instead of black when the notifications widget is open

- src/app/client-preview/page.tsx
- src/app/components/Footer.tsx
[Error in Client Home when content is null](https://linear.app/copilotplatforms/issue/OUT-407/error-in-client-home-when-content-is-null)
> OUT-407 Error in Client Home when content is null

- src/app/client-preview/page.tsx
- src/app/components/ClientPreview.tsx
- src/app/components/EditorInterface.tsx
- src/app/components/Footer.tsx
- src/app/page.tsx
- src/components/NotificationsModal/ModalCheckbox.tsx
- src/components/NotificationsModal/index.tsx
- src/components/tiptap/notificationWidget/NotificationWidget.tsx
- src/context/index.tsx
[The font for the client home page in the client portal does not reflect the font selected in the IU's customization setting](https://linear.app/copilotplatforms/issue/OUT-445/the-font-for-the-client-home-page-in-the-client-portal-does-not)
> OUT-445 The font for the client home page in the client portal does not reflect the font selected in the IU's customization setting

- src/utils/copilotApiUtils.ts
[OUT-789 | Certain CUs Missing from Preview Mode dropdown in Client Home](https://linear.app/copilotplatforms/issue/OUT-789/certain-cus-missing-from-preview-mode-dropdown-in-client-home)
> OUT-789 | Certain CUs Missing from Preview Mode dropdown in Client Home

- src/types/common.ts
[IU is receiving an error for Client Home app]([Task Link](https://linear.app/copilotplatforms/issue/OUT-1284/iu-is-receiving-an-error-for-client-home-app))
We updated how custom fields value can be returned. Previously it was either a string or array and now it can also be an object. This was causing a zodSchema defined in client home to fail and caused the page to crash.
Update the union in the zod schema to allow objects along side string and array.
I didn't spent too much time debugging this. Im going to open a sub-ticket for Outside to make this more robust. The whole app should not crash in cases like this.
> fix(OUT-1284): marketplace app support object for customField value

- src/app/client-preview/page.tsx
[No client with token client home error]([Task Link](https://linear.app/copilotplatforms/issue/POR-12904/no-client-with-token-client-home-error))
Check for customFields existing before iterating over them.
- this was a regression caused by a recent fix to show fullAddress in client home.
- we only tested when custom fields was present and not when it was not set.
> fix(POR-12904): client home not loading for clients without custom fields

- src/app/client-preview/page.tsx
> OUT-1436 | Use `clientId` from token payload and deprecate clientId search param

- src/app/components/Footer.tsx
- src/components/NotificationsModal/ModalCheckbox.tsx
- src/components/NotificationsModal/index.tsx
- src/components/tiptap/notificationWidget/NotificationWidget.tsx
- src/utils/font.ts
> OUT-1853: TypeError: t.appState.font.replaceAll is not a function

- .github/workflows/lint.yml
- Bump CI job node-version from 18 to 20
> OUT-2147 | Bump CI node-version to 20

- src/app/components/EditorInterface.tsx
> OUT-2269 | Client Home app: Save Changes Bar shows up once I install "Client home" app
